### ISSUE TITLE
If Font Folder is Missing:

### ISSUE THREAD

**Issue by GodWasaProgrammer** [GodWasaProgrammer/Bulk-Thumbnail-Creator#22]
blazor.server.js:1 [2023-10-30T16:17:40.889Z] Error: System.AggregateException: One or more errors occurred. (Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.) (Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.) (Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.) (Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Bulk_Thumbnail_Creator.DataGeneration.PickRandomFont() in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\DataGeneration.cs:line 119
   at Bulk_Thumbnail_Creator.Program.<>c__DisplayClass0_1.<Process>b__1(Int32 fileIndex) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\Program.cs:line 81
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Bulk_Thumbnail_Creator.Program.Process(ProductionType ProdType, String url, List`1 texts, PictureData PicdataObjToVarietize) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\Program.cs:line 63
   at Bulk_Thumbnail_Creator.Services.PictureDataService.CreateInitialPictureArrayAsync(String url, List`1 ListOfTextToPrint) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\PicService\PictureDataService.cs:line 30
   at BTC_Blazor.Pages.InputMenu.CallBTC(String url) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Pages\InputMenu.razor:line 52
   at BTC_Blazor.Pages.InputMenu.AwaitBTC() in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Pages\InputMenu.razor:line 77
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
 ---> (Inner Exception #1) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Bulk_Thumbnail_Creator.DataGeneration.PickRandomFont() in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\DataGeneration.cs:line 119
   at Bulk_Thumbnail_Creator.Program.<>c__DisplayClass0_1.<Process>b__1(Int32 fileIndex) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\Program.cs:line 81
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Bulk_Thumbnail_Creator.DataGeneration.PickRandomFont() in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\DataGeneration.cs:line 119
   at Bulk_Thumbnail_Creator.Program.<>c__DisplayClass0_1.<Process>b__1(Int32 fileIndex) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\Program.cs:line 81
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\BTCBlazor\Fonts'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Bulk_Thumbnail_Creator.DataGeneration.PickRandomFont() in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\DataGeneration.cs:line 119
   at Bulk_Thumbnail_Creator.Program.<>c__DisplayClass0_1.<Process>b__1(Int32 fileIndex) in C:\Users\vemha\Source\Repos\GodWasaProgrammer\Bulk-Thumbnail-Creator\Program.cs:line 81
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<--
   
   
Fiiiix

**Comment by GodWasaProgrammer** [comment]
This has been corrected by adding default fonts
